import JSZip from 'jszip';
import saveAs from 'file-saver';
import jEpub from 'jepub';

export interface Chapter {
  id: string;
  title: string;
  content: string;
  wordCount: number;
}

export interface BookMetadata {
  title: string;
  author: string;
  cover?: ArrayBuffer | null;
}

export async function generateEpub(chapters: Chapter[], metadata: BookMetadata) {
  try {
    const epub = new jEpub();

    epub.init({
      i18n: 'en',
      title: metadata.title,
      author: metadata.author,
      publisher: 'FanFicBinder',
      description: 'Generated by FanFicBinder',
      tags: ['Fanfiction', 'Binder'],
    });

    if (metadata.cover) {
      epub.cover(metadata.cover);
    }

    chapters.forEach((chapter) => {
      epub.add(chapter.title, chapter.content);
    });

    const blob = await epub.generate('blob');
    // Cast blob to Blob type as jepub might return other types but we requested 'blob'
    saveAs(blob as Blob, `${metadata.title.replace(/[^a-z0-9]/gi, '_')}.epub`);
    return true;
  } catch (error) {
    console.error("Error generating EPUB:", error);
    throw new Error("Failed to generate EPUB");
  }
}

// Mock API for fetching URL content
export async function mockFetchUrl(url: string): Promise<{ title: string; content: string }> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        title: `Chapter from ${new URL(url).hostname}`,
        content: `
          <p>This is a simulated chapter content fetched from <strong>${url}</strong>.</p>
          <p>In a real implementation, this would be the result of parsing the HTML with JSDOM and Readability.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        `
      });
    }, 1500);
  });
}
